DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS nutrition;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE nutrition (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    calories INTEGER NOT NULL,
    FOREIGN KEY (person_id) REFERENCES user (id)
);
