on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract number of commits
        shell: bash
        run: echo "##[set-output name=diff;]$(echo $(git for-each-ref --format="%(push:track)" refs/heads/$(git rev-parse --abbrev-ref HEAD)))"
        id: extract_commits
      - name: git
        run: |
          git --version
          git rev-list --left-right --count ${{ steps.extract_branch.outputs.branch }}...origin/main
      - name: Hello world action step
        id: hello
        uses: joshfeld/jf_test_action@v1
        with:
          commit-diff: ${{ steps.extract_commits.outputs.diff }}
          branch-name: ${{ steps.extract_branch.outputs.branch }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
